# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vjNNsnGbdifF_-7J23ZrKiGU9hhMTbmZ
"""

import pandas as pd
import numpy as np

df=pd.read_csv('Titanic-Dataset.csv')

df.head(3)

from sklearn.preprocessing import LabelEncoder

df=df.drop(columns=['PassengerId','Name','Ticket','Cabin'],errors='ignore')
df.head(3)

label_encoder={}
for columns in ['Sex','Embarked']:
    le=LabelEncoder()
    df[columns]=le.fit_transform(df[columns])
    label_encoder[columns]=le

# Eksik değerleri doldur
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Fare'].fillna(df['Fare'].mean(), inplace=True)

X=df.drop('Survived',axis=1)
y=df['Survived']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,y_train)

from sklearn.metrics import accuracy_score,classification_report
y_pred=model.predict(X_test)
print("Dogruluk orani",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

from sklearn import tree
import matplotlib.pyplot as plt
plt.figure(figsize=(20,10))
tree.plot_tree(model,feature_names=X.columns,class_names=["Not Survived","Survived"],filled=True)
plt.show()

